### PR TITLE
Fix typo that causes vignette to fail

### PR DESCRIPTION
**Pull request by seandavi**

### CODE REVIEW

**Comment by seandavi** [comment]
If you could take a look at this soon and merge, the vignette will then build. 

Thanks for taking a quick look.

**Comment by seaYali** [comment]
Hello Sean,

   Sorry about that. I just fixed it.
   Thanks,
Haibo

**Comment by seandavi** [comment]
No problem. Thanks for the quick fix. The vignette now builds--yeah!

**Comment by seaYali** [comment]
Thank you, Sean.
Haibo

**Pull request closed without merging**
